### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by wa-crashreporter** [WycliffeAssociates/5WoC#1139]
Environment
======
Environment Key | Value
:----: | :----:
version | 1.3.2-rc
build | 15
UDID | a0cf749ee9b4f4b5
Android Release | 9
Android SDK | 28
Brand | google
Device | bonito
Stack trace
======
```java
java.lang.SecurityException: Permission Denial: startForeground from pid=20946, uid=10155 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5202)
	at android.app.Service.startForeground(Service.java:695)
	at net.gotev.uploadservice.UploadService.holdForegroundNotification(UploadService.java:388)
	at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:469)
	at net.gotev.uploadservice.UploadTask.run(UploadTask.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9204)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1189)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:870)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20503)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:977)


```
Log history
======
```java
7/3/19 9:36 AM  W/org.wycliffeassociates.translationrecorder.MainMenu@6eb54f6: SUCCESS: Log file initialized.
7/3/19 9:36 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2279ca9: Recent Project: language en book mat version reg mode verse
7/3/19 9:36 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2279ca9: Recent Project: language en book mat version reg mode verse
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@2279ca9: Recent Project: language en book mat version reg mode verse
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Playback.PlaybackActivity@5148cae: onCreate
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Recording screen onPauseRecording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: SUCCESS: exited queues, took 28 to finish writing
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression queue finishing, sending done message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: exited compression thread loop
7/3/19 9:35 AM  E/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio queue finishing, sending done message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread writing remaining data
7/3/19 9:35 AM  E/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio queue finishing, sending done message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread exited loop
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread received a stop message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread exited loop
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread received a stop message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread received a stop message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.AudioVisualization.ActiveRecordingRenderer$1@dc2c60a: UI thread received a stop message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Stopping recording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Stop
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Pausing recording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Pause
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Record
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Pausing recording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Pause
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Record
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Pausing recording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Pause
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Pausing recording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Pause
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Record
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: Compression thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@63f92b2: raw audio thread received a onPauseRecording message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@b06e0e1: Pausing recording
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@dd7ecbd: created a new vis file
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@38e8c14: starting compression thread
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Pause
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.AudioVisualization.ActiveRecordingRenderer$1@d1ac168: UI thread received a stop message
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@bb86c8b: User pressed Record
7/3/19 9:35 AM  W/RecordingActivity: Creating New Recording Intent
7/3/19 9:35 AM  W/org.wycliffeassociates.translationrecorder.MainMenu@7c75283: SUCCESS: Log file initialized.
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Playback.PlaybackActivity@905b52c: onDisableVerseMarkerMode
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Playback.PlaybackActivity@905b52c: onEnableVerseMarkerMode
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Playback.Editing.CutOp@eafe0e0: Generating flattened stack and computing time removed
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Playback.Editing.CutOp@eafe0e0: Generating location stacks
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Playback.Editing.CutOp@eafe0e0: Generating flattened stack and computing time removed
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Playback.PlaybackActivity@905b52c: onCreate
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Recording screen onPauseRecording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: SUCCESS: exited queues, took 23 to finish writing
7/3/19 9:34 AM  E/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio queue finishing, sending done message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread exited loop
7/3/19 9:34 AM  E/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio queue finishing, sending done message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread exited loop
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a stop message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.AudioVisualization.ActiveRecordingRenderer$1@45949da: UI thread received a stop message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a stop message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression queue finishing, sending done message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: exited compression thread loop
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread writing remaining data
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a stop message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Stopping recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Stop
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Record
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Record
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Record
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Record
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: Compression thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.RecordingActivity@dae3438: Pausing recording
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$3@7f97d64: created a new vis file
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$1@d44eaf7: raw audio thread received a onPauseRecording message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.WavFileWriter$2@ad816f6: starting compression thread
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Pause
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.AudioVisualization.ActiveRecordingRenderer$1@c24022a: UI thread received a stop message
7/3/19 9:34 AM  W/org.wycliffeassociates.translationrecorder.Recording.fragments.FragmentRecordingControls$2@1030f15: User pressed Record
7/3/19 9:33 AM  W/RecordingActivity: Creating New Recording Intent
7/3/19 9:31 AM  W/org.wycliffeassociates.translationrecorder.MainMenu@261e0: SUCCESS: Log file initialized.
     

```

**Comment by danparisd** [comment]
this was a test
