### ISSUE TITLE
test crash

### ISSUE THREAD

**Issue by wa-crashreporter** [WycliffeAssociates/5WoC#1140]
Notes
======
test crash

Environment
======
Environment Key | Value
:----: | :----:
version | 1.3.2-rc
build | 15
UDID | a0cf749ee9b4f4b5
Android Release | 9
Android SDK | 28
Brand | google
Device | bonito
Stack trace
======
```java
java.lang.SecurityException: Permission Denial: startForeground from pid=21222, uid=10155 requires android.permission.FOREGROUND_SERVICE
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.os.Parcel.readException(Parcel.java:1868)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5202)
	at android.app.Service.startForeground(Service.java:695)
	at net.gotev.uploadservice.UploadService.holdForegroundNotification(UploadService.java:388)
	at net.gotev.uploadservice.UploadTask.createNotification(UploadTask.java:469)
	at net.gotev.uploadservice.UploadTask.run(UploadTask.java:145)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9204)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1189)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:870)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20503)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:977)


```
Log history
======
```java
7/3/19 9:37 AM  W/org.wycliffeassociates.translationrecorder.MainMenu@c02e269: SUCCESS: Log file initialized.
7/3/19 9:36 AM  W/org.wycliffeassociates.translationrecorder.ProjectManager.activities.ActivityProjectManager@b0f1350: Recent Project: language en book mat version reg mode verse
     

```

**Comment by danparisd** [comment]
this was a test
